apiVersion: v1
data:
  postgresHost: 10.127.144.3
  postgresPort: "5432"
  postgresDb: prim-r-db
  redisHost: 10.0.0.3
  redisPort: "6379"
  springProfilesActive: staging
kind: ConfigMap
metadata:
  creationTimestamp: 2019-03-29T21:43:41Z
  name: managed-services
  namespace: jx-staging
  resourceVersion: "55593"
  selfLink: /api/v1/namespaces/jx-staging/configmaps/managed-services
  uid: b847996e-526b-11e9-afd8-42010a9c0090
