apiVersion: v1
data:
  password: Y2hhbmdlbWU=
  user: ZGItdXNlcg==
kind: Secret
metadata:
  creationTimestamp: 2019-03-29T21:01:06Z
  name: postgres-secret
  namespace: jx-staging
  resourceVersion: "47504"
  selfLink: /api/v1/namespaces/jx-staging/secrets/postgres-secret
  uid: c5128b30-5265-11e9-afd8-42010a9c0090
type: Opaque
